spring:
  datasource:
    url: jdbc:h2:mem:pet_store;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-pets
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create